spring.application.name=ladafura

# ==========================================
# Configuration Firebase Admin SDK
# ==========================================
firebase.config.path=${FIREBASE_CONFIG_PATH:classpath:firebase-service-account.json}